# Generated by Django 4.2.2 on 2023-07-01 15:29

import artgallery.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, default=artgallery.models.get_default_profile_image, max_length=255, null=True, upload_to=artgallery.models.get_profile_img_filepath)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('activity', models.CharField(choices=[('visual_arts', 'Visual arts'), ('fine_art', 'Fine art'), ('conceptual_art', 'Conceptual art'), ('sculpture', 'Sculpture'), ('painting', 'Painting'), ('installation_art', 'Installation art'), ('drawing', 'Drawing'), ('illustration', 'Illustration'), ('decorative_arts', 'Decorative arts'), ('abstract_art', 'Abstract art'), ('mixed_media', 'Mixed media'), ('digital_art', 'Digital art'), ('applied_arts', 'Applied arts'), ('pop_art', 'Pop art')], max_length=50)),
                ('instagram_username', models.CharField(max_length=50, verbose_name='Instagram')),
                ('twitter_username', models.CharField(max_length=50, verbose_name='Twitter')),
                ('linkedin_username', models.CharField(max_length=50, verbose_name='Linkedin')),
                ('pinterest_username', models.CharField(max_length=50, verbose_name='Pinterest')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of art work')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('score', models.PositiveSmallIntegerField(verbose_name=range(1, 11))),
                ('style', models.CharField(choices=[('visual_arts', 'Visual arts'), ('fine_art', 'Fine art'), ('conceptual_art', 'Conceptual art'), ('sculpture', 'Sculpture'), ('painting', 'Painting'), ('installation_art', 'Installation art'), ('drawing', 'Drawing'), ('illustration', 'Illustration'), ('decorative_arts', 'Decorative arts'), ('abstract_art', 'Abstract art'), ('mixed_media', 'Mixed media'), ('digital_art', 'Digital art'), ('applied_arts', 'Applied arts'), ('pop_art', 'Pop art')], max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('option', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artgallery.artist')),
            ],
        ),
    ]
